services:
  - type: web
    name: bridgesec-data-transformer-dev
    env: python
    plan: free  # or 'starter', 'standard', etc.
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn bridgesec_data_transformer.wsgi:application
    envVars:
      - key: DEBUG
      - key: OKTA_DOMAIN
      - key: OKTA_TOKEN
      - key: MONGO_DB_NAME
      - key: MONGO_URI
      