services:
  - type: web
    name: bridgesec_data_transformer
    env: python
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn bridgesec_data_transformer.wsgi:application --chdir bridgesec_data_transformer
    envVars:
      - fromGroup: Bridgesec