services:
  - type: web
    name: bridgesec-data-transformer
    env: python
    plan: free
    branch: main
    buildCommand: |
      cd bridgesec_data_transformer
      pip install -r ../requirements.txt
      python manage.py collectstatic --noinput
    startCommand: >
       gunicorn bridgesec_data_transformer.wsgi:application
       --chdir bridgesec_data_transformer
       --timeout 2000
    envVars:
      - fromGroup: Bridgesec
    healthCheckPath: /
