services:
  - type: web
    name: bridgesec-django
    env: docker
    branch: dev
    plan: free
    dockerfilePath: bridgesec_data_transformer/Dockerfile
    startCommand: >
      gunicorn bridgesec_data_transformer.wsgi:application
      --chdir bridgesec_data_transformer
      --bind 0.0.0.0:8000
      --timeout 2000
    envVars:
      - fromGroup: Bridgesec
    healthCheckPath: /

  - type: worker
    name: bridgesec-celery
    env: docker
    branch: dev
    plan: free
    dockerfilePath: bridgesec_data_transformer/Dockerfile
    startCommand: >
      sh -c 'celery -A bridgesec_data_transformer worker --loglevel=INFO 2>&1 | tee -a /app/logs/app.log'
    envVars:
      - fromGroup: Bridgesec

  - type: worker
    name: bridgesec-consumer
    env: docker
    branch: dev
    plan: free
    dockerfilePath: bridgesec_data_transformer/Dockerfile
    startCommand: python core/rabbitmq_consumer.py
    envVars:
      - fromGroup: Bridgesec
