services:
  - type: web
    name: bridgesec_data_transformer
    env: python
    plan: free  # or 'starter', 'standard', etc.
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn bridgesec_data_transformer.wsgi:application
    envVars:
      -fromGroup: Bridgesec

