services:
  - type: web
    name: bridgesec-django
    env: docker
    plan: free
    branch: dev
    dockerfilePath: Dockerfile
    envVars:
      - fromGroup: Bridgesec
    ports:
      - 8000
    healthCheckPath: /
