services:
  - type: web
    name: bridgesec-django
    env: docker
    plan: free
    branch: dev
    dockerfilePath: bridgesec_data_transformer/Dockerfile
    envVars:
      - fromGroup: Bridgesec
    healthCheckPath: /
