from rest_framework import serializers

class DeviceAndroidSerializer(serializers.Serializer):
    name = serializers.CharField(required=True)
    os_version = serializers.CharField(required=False)
    disk_encryption_type = serializers.ListField(required=False)
    jailbreak = serializers.BooleanField(required=False)
    secure_hardware_present = serializers.BooleanField(required=False)
    screenlock_type = serializers.ListField(required=False)

class DeviceIosSerializer(serializers.Serializer):
    name = serializers.CharField(required=True)
    os_version = serializers.CharField(required=False)
    jailbreak = serializers.BooleanField(required=False)
    screenlock_type = serializers.ListField(required=False)

class DeviceMacOSSerializer(serializers.Serializer):
    name = serializers.CharField(required=True)
    os_version = serializers.CharField(required=False)
    disk_encryption_type = serializers.ListField(required=False)
    secure_hardware_present = serializers.BooleanField(required=False)
    screenlock_type = serializers.ListField(required=False)
    third_party_signal_providers = serializers.BooleanField(required=False)
    tpsp_browser_version = serializers.CharField(required=False)
    tpsp_builtin_dns_client_enabled = serializers.BooleanField(required=False)
    tpsp_chrome_remote_desktop_app_blocked = serializers.BooleanField(required=False)
    tpsp_device_enrollment_domain = serializers.CharField(required=False)
    tpsp_disk_encrypted = serializers.BooleanField(required=False)
    tpsp_key_trust_level = serializers.CharField(required=False)
    tpsp_os_firewall = serializers.BooleanField(required=False)
    tpsp_os_version = serializers.CharField(required=False)
    tpsp_password_protection_warning_trigger = serializers.CharField(required=False)
    tpsp_realtime_url_check_mode = serializers.BooleanField(required=False)
    tpsp_safe_browsing_protection_level = serializers.CharField(required=False)
    tpsp_screen_lock_secured = serializers.BooleanField(required=False)
    tpsp_site_isolation_enabled = serializers.BooleanField(required=False)

class DeviceWindowsSerializer(serializers.Serializer):
    name = serializers.CharField(required=True)
    os_version = serializers.CharField(required=False)
    secure_hardware_present = serializers.BooleanField(required=False)
    screenlock_type = serializers.ListField(required=False)
    third_party_signal_providers = serializers.BooleanField(required=False)
    tpsp_browser_version = serializers.CharField(required=False)
    tpsp_builtin_dns_client_enabled = serializers.BooleanField(required=False)
    tpsp_chrome_remote_desktop_app_blocked = serializers.BooleanField(required=False)
    tpsp_crowd_strike_agent_id = serializers.CharField(required=False)
    tpsp_crowd_strike_customer_id = serializers.CharField(required=False)
    tpsp_device_enrollment_domain = serializers.CharField(required=False)
    tpsp_disk_encrypted = serializers.BooleanField(required=False)
    tpsp_key_trust_level = serializers.CharField(required=False)
    tpsp_os_firewall = serializers.BooleanField(required=False)
    tpsp_os_version = serializers.CharField(required=False)
    tpsp_password_protection_warning_trigger = serializers.CharField(required=False)
    tpsp_realtime_url_check_mode = serializers.BooleanField(required=False)
    tpsp_safe_browsing_protection_level = serializers.CharField(required=False)
    tpsp_screen_lock_secured = serializers.BooleanField(required=False)
    tpsp_secure_boot_enabled = serializers.BooleanField(required=False)
    tpsp_secure_isolation_enabled = serializers.BooleanField(required=False)
    tpsp_third_party_blocking_enabled = serializers.BooleanField(required=False)
    tpsp_windows_machine_domain = serializers.CharField(required=False)
    tpsp_windows_user_domain = serializers.CharField(required=False)