"""
Django settings for bridgesec_data_transformer project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

import environ
from core.utils.mongo_utils import connect_to_mongo
from mongoengine import connect
from pymongo import MongoClient

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env()
environ.Env.read_env(os.path.join(BASE_DIR.parent, '.env'))


OKTA_API_URL = env("OKTA_API_URL")
OKTA_API_TOKEN = env("OKTA_API_TOKEN", default=None)
OKTA_CLIENT_ID = env("OKTA_CLIENT_ID")
OKTA_REDIRECT_URI = env("OKTA_REDIRECT_URI")
OKTA_ISSUER = env("OKTA_ISSUER")
OKTA_SECRET_KEY = env("OKTA_SECRET_KEY")
FRONTEND_REDIRECT_URL = env("FRONTEND_REDIRECT_URL")
FRONTEND_URL = env("FRONTEND_URL")
SERVER_URL = env("SERVER_URL")

# Supabase Configuration (for Terraform state file verification)
# Add these to your .env file:
#   SUPABASE_URL=https://your-project.supabase.co
#   SUPABASE_KEY=your-anon-key-here
#   SUPABASE_BUCKET=terraform-states
SUPABASE_URL = env("SUPABASE_URL", default=None)
SUPABASE_KEY = env("SUPABASE_KEY", default=None)
SUPABASE_BUCKET = env("SUPABASE_BUCKET", default="terraform-states")

# Okta OAuth Scopes for API access
# These scopes are requested during login to access Okta Admin APIs
OKTA_SCOPES = " ".join([
    # OpenID Connect scopes
    "openid",
    "email",
    "profile",
    # Okta Admin API scopes
    "okta.users.read",
    "okta.apps.read",
    "okta.groups.read",
    "okta.policies.read",
    "okta.authorizationServers.read",
    "okta.authorizationServers.manage",
    "okta.userTypes.manage",
    "okta.userTypes.manage",

    # "okta.idps.read",
    "okta.brands.read",
    "okta.brands.manage",
    "okta.authenticators.read",
    # "okta.orgs.read",
    "okta.eventHooks.read",
    "okta.inlineHooks.read",
    "okta.behaviors.read",
    "okta.deviceAssurance.read",
    "okta.emailServers.read",
    "okta.emailDomains.read",
    "okta.users.manage.self",
    "okta.users.manage",
    "okta.groups.manage",
    "okta.directories.groups.manage",
    "okta.apps.manage",
    "okta.schemas.manage",
    "okta.groups.manage",
    "okta.idps.manage",
    "okta.idps.read",
    "okta.profileMappings.read",
    "okta.profileMappings.manage",
    "okta.policies.manage",
    # "okta.networkZones.read",
    "okta.trustedOrigins.read",
    # "okta.templates.read",
    # "okta.threatInsights.read",
    "okta.rateLimits.read",
    "okta.roles.read",
    # "okta.resourceSets.read",
    # "okta.captchas.read",
    "okta.schemas.read",
    "okta.userTypes.read",
    "okta.users.manage.self",
    "okta.users.manage",
    "okta.apps.manage",
    # "okta.clients.read",
    "okta.factors.read",
    # "okta.logs.read",
    # "okta.devices.read",
])

# Mapping of Okta API endpoints to required scopes (for error handling)
# Values can be a single scope string or a list of scopes for endpoints that need multiple permissions
OKTA_API_SCOPE_MAP = {
    # Users endpoint requires multiple scopes for all sub-entities
    "/users": [
        "okta.users.read",
        "okta.roles.read",
        "okta.schemas.read",
        "okta.userTypes.read",
        "okta.factors.read",
        "okta.users.manage.self",
        "okta.users.manage"
    ],
    # Apps endpoint requires multiple scopes for all sub-entities
    "/apps": [
        "okta.apps.read",
        "okta.policies.read",
        "okta.schemas.read",
        "okta.roles.read",
    ],
    "/groups": "okta.groups.read",
    "/policies": "okta.policies.read",
    "/authorizationServers": "okta.authorizationServers.read",
    "/idps": ["okta.idps.read", "okta.idps.manage", "okta.profileMappings.read", "okta.profileMappings.manage"],
    # Brands endpoint requires multiple scopes for sub-entities
    "/brands": [
        "okta.brands.read",
        "okta.emailDomains.read",
    ],
    # Authenticators endpoint requires multiple scopes
    "/authenticators": [
        "okta.authenticators.read",
        "okta.factors.read",
    ],
    # "/org": "okta.orgs.read",
    "/eventHooks": "okta.eventHooks.read",
    "/inlineHooks": "okta.inlineHooks.read",
    "/behaviors": "okta.behaviors.read",
    "/device-assurances": "okta.deviceAssurance.read",
    "/email-servers": "okta.emailServers.read",
    "/email-domains": "okta.emailDomains.read",
    # "/zones": "okta.networkZones.read",
    "/trustedOrigins": "okta.trustedOrigins.read",
    # "/templates": "okta.templates.read",
    # "/threats": "okta.threatInsights.read",
    "/rate-limit": "okta.rateLimits.read",
    "/principal-rate-limits": "okta.rateLimits.read",
    "/iam/roles": "okta.roles.read",
    # "/iam/resource-sets": "okta.resourceSets.read",
    # "/captchas": "okta.captchas.read",
    "/meta/schemas": "okta.schemas.read",
    "/meta/types": "okta.userTypes.read",
    # "/oauth2/v1/clients": "okta.clients.read",
    "/factors": "okta.factors.read",
    # "/logs": "okta.logs.read",
    # "/devices": "okta.devices.read",
}

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DEBUG", default=False)

ALLOWED_HOSTS = [
    '.onrender.com',
    '127.0.0.1',
    '31.97.229.6',
    "localhost"
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'drf_yasg',
    'core',
    'entities',
    'rest_framework_simplejwt',
    'corsheaders',

]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'bridgesec_logging.middleware.LoggingMiddleware',  # Centralized logging middleware
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware'
]

ROOT_URLCONF = 'bridgesec_data_transformer.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'bridgesec_data_transformer.wsgi.application'
ASGI_APPLICATION = 'bridgesec_data_transformer.asgi.application'

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("127.0.0.1", 6379)], 
        },
    },
}

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases



# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

SESSION_COOKIE_HTTPONLY = False
SESSION_COOKIE_SECURE = False          # Only if using HTTPS
SESSION_COOKIE_SAMESITE = "Lax" 


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATIC_URL = '/static/'
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"
# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


MONGO_DB_NAME = env("MONGO_DB_NAME")
MONGO_URI = env("MONGO_URI")
MONGO_CLIENT = MongoClient(MONGO_URI)

connect(db=MONGO_DB_NAME, host=MONGO_URI)
connect_to_mongo()
MONGO_CONNECTIONS = set()

# ========================================
# LOGGING CONFIGURATION
# ========================================
# Setup structured logging with Loki integration
try:
    from bridgesec_logging import setup_logging
    setup_logging(
        app_name="bridgesec",
        log_dir=BASE_DIR / 'logs',
        environment=os.getenv('ENVIRONMENT', 'development'),
        log_level='DEBUG',  # TEMPORARY: Set to DEBUG to see access token logs
        enable_loki=False,  # Disable Loki to prevent logging issues
    )
except Exception as e:
    import logging
    logging.warning(f"Failed to setup Loki logging: {e}. Using default logging.")

# Logging configuration
PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
LOG_DIR = os.path.join(PROJECT_ROOT, 'logs')

if not os.path.exists(LOG_DIR):
    os.makedirs(LOG_DIR)


# CLIENT_ID = env("CLIENT_ID")
# ISSUER_URL = env("ISSUER_URL")

CORS_ALLOWED_ORIGINS = [
    "http://127.0.0.1:3000",
    "https://bridgesec-fe.vercel.app",
    "http://31.97.229.6:3000",
    "http://localhost:3000"
]

CORS_ALLOW_CREDENTIALS = True

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,

    'formatters': {
        'verbose': {
            'format': '{asctime} | {levelname} | {module}.{funcName}:{lineno} | {message}',
            'style': '{',
        },
        'json': {
            '()': 'pythonjsonlogger.jsonlogger.JsonFormatter',
            'format': '%(asctime)s %(levelname)s %(name)s %(module)s %(funcName)s %(lineno)d %(message)s',
            'datefmt': '%Y-%m-%dT%H:%M:%S',
        },
        'colored': {
            '()': 'colorlog.ColoredFormatter',
            'format': '%(log_color)s%(asctime)s | %(levelname)s | %(module)s.%(funcName)s:%(lineno)d | %(message)s',
            'datefmt': '%Y-%m-%d %H:%M:%S',
            'log_colors': {
                'DEBUG': 'cyan',
                'INFO': 'green',
                'WARNING': 'yellow',
                'ERROR': 'red',
                'CRITICAL': 'bold_red',
            },
        },
    },

    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'colored',
            'level': 'DEBUG',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': os.path.join(LOG_DIR, 'app.log'),
            'formatter': 'verbose',
            'level': 'DEBUG',

        },
        'celery_file': {
            'class': 'logging.FileHandler',
            'filename': os.path.join(LOG_DIR, 'bridgesec_celery.log'),
            'formatter': 'json',
            'level': 'DEBUG',
        },
        'error_file': {
            'class': 'logging.FileHandler',
            'filename': os.path.join(LOG_DIR, 'error.log'),
            'formatter': 'verbose',
            'level': 'ERROR',
        },
    },

    'loggers': {
        # Default logger for all modules
        '': {
            'handlers': ['console', 'file', 'error_file'],
            'level': 'INFO',
            'propagate': True,
        },
         "celery": {
            "handlers": ["console", "celery_file"],
            "level": "INFO",
            "propagate": False,
        },
        "pika": {
            "handlers": ["file"],
            "level": "WARNING",  # suppress INFO logs from pika
            "propagate": False,
        },
        "urllib3": {
            "handlers": ["file"],
            "level": "WARNING",  # suppress verbose HTTP logs
            "propagate": False,
        },
    },
}

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "core.authentication.CustomJWTAuthentication",
    )
}


SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,
}

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

SWAGGER_SETTINGS = {
    'SECURITY_DEFINITIONS': {
        'Bearer': {
            'type': 'apiKey',
            'name': 'Authorization',
            'in': 'header'
        }
    },
    "USE_SESSION_AUTH": False,   # hides Django login/logout
    "LOGIN_URL": None,
    "LOGOUT_URL": None,
}

CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL")
CELERY_RESULT_BACKEND = "rpc://"  # or another backend like MongoDB or Redis
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'

