"""
Django settings for bridgesec_data_transformer project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env()
environ.Env.read_env(os.path.join(BASE_DIR.parent, '.env'), overwrite=False)


# OKTA_API_URL = env("OKTA_API_URL")
# OKTA_API_TOKEN = env("OKTA_API_TOKEN", default=None)
# OKTA_CLIENT_ID = env("OKTA_CLIENT_ID")
# OKTA_ISSUER = env("OKTA_ISSUER")
# OKTA_SECRET_KEY = env("OKTA_SECRET_KEY")
OKTA_REDIRECT_URI = env("OKTA_REDIRECT_URI")
FRONTEND_REDIRECT_URL = env("FRONTEND_REDIRECT_URL")
FRONTEND_URL = env("FRONTEND_URL")
SERVER_URL = env("SERVER_URL")
BRIDGESEC_API_URL = env("BRIDGESEC_API_URL", default="http://localhost:8007")

# ── Multi-tenancy ────────────────────────────────────────────────────────────
# Set MULTI_TENANCY_ENABLED=True to activate per-tenant isolation.
# When False (default) ALL multi-tenant code is bypassed and the app behaves
# exactly as before (single-tenant).
MULTI_TENANCY_ENABLED = env.bool("MULTI_TENANCY_ENABLED", default=False)

# Master database — stores Tenant and ActivityLog documents.
# Defaults to the same Mongo URI / DB as the single-tenant setup so no
# migration is required on first deploy.
MASTER_MONGO_URI = env("MASTER_MONGO_URI", default=None)   # None → falls back to MONGO_URI
MASTER_DB_NAME = env("MASTER_DB_NAME", default="bridgesec_master")

# Service App OAuth 2.0 Client Credentials (for scheduled tasks)
# Used by Celery Beat to get an access token without a user session.
# The service app must have scopes pre-granted in Okta Admin Console.
OKTA_SERVICE_CLIENT_ID = env("OKTA_SERVICE_CLIENT_ID", default=None)
OKTA_SERVICE_PRIVATE_KEY = env("OKTA_SERVICE_PRIVATE_KEY", default=None)
OKTA_SERVICE_SCOPES = env("OKTA_SERVICE_SCOPES", default="")

# Chat model providers — /api/chat/. See docs/CHAT_MODEL_PROVIDERS.md
CHAT_PROVIDER = env("CHAT_PROVIDER", default="anthropic")   # "anthropic" | "groq"
CHAT_TIMEOUT  = env.int("CHAT_TIMEOUT", default=120)

ANTHROPIC_API_KEY = env("ANTHROPIC_API_KEY", default=None)
ANTHROPIC_MODEL   = env("ANTHROPIC_MODEL", default="claude-sonnet-4-6")

GROQ_API_KEY  = env("GROQ_API_KEY", default=None)
GROQ_MODEL    = env("GROQ_MODEL", default="llama-3.3-70b-versatile")
GROQ_BASE_URL = env("GROQ_BASE_URL", default="https://api.groq.com/openai/v1")

# Supabase Configuration (for Terraform state file verification)
# Add these to your .env file:
#   SUPABASE_URL=https://your-project.supabase.co
#   SUPABASE_KEY=your-anon-key-here
#   SUPABASE_BUCKET=terraform-states
SUPABASE_URL = env("SUPABASE_URL", default=None)
SUPABASE_KEY = env("SUPABASE_SERVICE_ROLE_KEY", default=None)
SUPABASE_BUCKET = env("SUPABASE_BUCKET", default="terraform-states")
# TTL (seconds) for the in-process Supabase-backed mapping cache.
# Set shorter in dev (e.g. 30) so that re-seeding takes effect quickly.
MAPPINGS_CACHE_TTL_SEC = env.int("MAPPINGS_CACHE_TTL_SEC", default=300)

# Okta OAuth Scopes for API access
# These scopes are requested during login to access Okta Admin APIs
OKTA_SCOPES = " ".join([
    # OpenID Connect scopes
    "openid",
    "email",
    "profile",
    # Okta Admin API scopes
    "okta.authorizationServers.manage",
    "okta.userTypes.manage",
    "okta.userTypes.manage",
    "okta.idps.manage",
    "okta.brands.manage",
    "okta.authenticators.read",
    # "okta.orgs.read",
    "okta.eventHooks.read",
    "okta.inlineHooks.read",
    "okta.inlineHooks.manage",
    "okta.behaviors.read",
    "okta.deviceAssurance.read",
    "okta.emailServers.read",
    "okta.emailDomains.read",
    "okta.groups.manage",
    "okta.directories.groups.manage",
    "okta.apps.manage",
    "okta.schemas.manage",
    "okta.groups.manage",
    "okta.profileMappings.read",
    "okta.profileMappings.manage",
    "okta.policies.manage",
    # "okta.networkZones.read",
    "okta.trustedOrigins.read",
    # "okta.templates.read",
    # "okta.threatInsights.read",
    "okta.rateLimits.read",
    "okta.roles.read",
    "okta.roles.manage",
    # "okta.resourceSets.read",
    # "okta.captchas.read",
    "okta.schemas.read",
    "okta.appGrants.manage",
    "okta.userTypes.read",
    "okta.users.manage.self",
    "okta.appGrants.manage",
    "okta.logs.read",
    "okta.users.manage",
    "okta.apps.manage",
    # "okta.clients.read",
    "okta.factors.read",
    # "okta.logs.read",
    # "okta.devices.read",
])

# Mapping of Okta API endpoints to required scopes (for error handling)
# Values can be a single scope string or a list of scopes for endpoints that need multiple permissions
OKTA_API_SCOPE_MAP = {
    # Users endpoint requires multiple scopes for all sub-entities
    "/users": [
        "okta.users.read",
        "okta.roles.read",
        "okta.schemas.read",
        "okta.userTypes.read",
        "okta.factors.read",
        "okta.users.manage.self",
        "okta.users.manage"
    ],
    # Apps endpoint requires multiple scopes for all sub-entities
    "/apps": [
        "okta.apps.read",
        "okta.policies.read",
        "okta.schemas.read",
        "okta.roles.read",
    ],
    "/groups": "okta.groups.read",
    "/policies": "okta.policies.read",
    "/authorizationServers": "okta.authorizationServers.read",
    "/idps": [
        "okta.idps.read",
        "okta.idps.manage"
    ],
    # Brands endpoint requires multiple scopes for sub-entities
    "/brands": [
        "okta.brands.read",
        "okta.emailDomains.read",
    ],
    # Authenticators endpoint requires multiple scopes
    "/authenticators": [
        "okta.authenticators.read",
        "okta.factors.read",
    ],
    # "/org": "okta.orgs.read",
    "/eventHooks": "okta.eventHooks.read",
    "/inlineHooks": "okta.inlineHooks.read",
    "/behaviors": "okta.behaviors.read",
    "/device-assurances": "okta.deviceAssurance.read",
    "/email-servers": "okta.emailServers.read",
    "/email-domains": "okta.emailDomains.read",
    # "/zones": "okta.networkZones.read",
    "/trustedOrigins": "okta.trustedOrigins.read",
    # "/templates": "okta.templates.read",
    # "/threats": "okta.threatInsights.read",
    "/rate-limit": "okta.rateLimits.read",
    "/principal-rate-limits": "okta.rateLimits.read",
    "/iam/roles": "okta.roles.read",
    # "/iam/resource-sets": "okta.resourceSets.read",
    # "/captchas": "okta.captchas.read",
    "/meta/schemas": "okta.schemas.read",
    "/meta/types": "okta.userTypes.read",
    # "/oauth2/v1/clients": "okta.clients.read",
    "/factors": "okta.factors.read",
    # "/logs": "okta.logs.read",
    # "/devices": "okta.devices.read",
}

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DEBUG", default=False)
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=[
    '.onrender.com',
    '127.0.0.1',
    '31.97.229.6',
    "localhost",
    "jaggiest-stephania-autonomously.ngrok-free.dev",
])

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'drf_yasg',
    'core.apps.CoreConfig',
    'entities.apps.EntitiesConfig',
    'rest_framework_simplejwt',
    'corsheaders',
    'dotenv',

]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'bridgesec_logging.middleware.LoggingMiddleware',  # Centralized logging middleware
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    # 'core.middleware.tenant_middleware.TenantContextMiddleware',  # Attach request._tenant
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware'
]

ROOT_URLCONF = 'bridgesec_data_transformer.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'bridgesec_data_transformer.wsgi.application'
ASGI_APPLICATION = 'bridgesec_data_transformer.asgi.application'

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("127.0.0.1", 6379)],
        },
    },
}

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases



# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

SESSION_COOKIE_HTTPONLY = True  # session cookie must not be readable by JavaScript (XSS -> session theft)
# SESSION_COOKIE_SECURE = False          # Only if using HTTPS
# SESSION_COOKIE_SAMESITE = "Lax"


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATIC_URL = '/static/'
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"
# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


MONGO_DB_NAME = env("MONGO_DB_NAME", default="bridgesec")
MONGO_URI     = env("MONGO_URI", default="")

# MONGO_CLIENT is intentionally None at startup.
# All request-handling code uses tenant-specific clients resolved from Supabase
# via request._mongo_client. get_system_mongo_client() provides a lazy fallback
# for control-plane collections (progress tracking, scheduled tasks).
MONGO_CLIENT = None

# MongoEngine default connection is also deferred — per-db aliases are registered
# on demand inside ensure_mongo_connection(). No startup connection needed.
MONGO_CONNECTIONS = set()

# Elasticsearch Configuration (for log querying)
ELASTICSEARCH_URL = env("ELASTICSEARCH_URL", default="http://localhost:9200")

# Splunk / Loki logging backends — we host one shared instance of each; a
# tenant only picks WHICH backend (tenants.logging_backend), never brings
# their own server/credentials. Same pattern as ELASTICSEARCH_URL above.
#
# Splunk needs separate write (HEC) vs read (Search API) credentials because
# those are two distinct Splunk subsystems on different ports with different
# auth — a HEC token can't run a search, and search creds can't post to HEC.
SPLUNK_HEC_URL         = env("SPLUNK_HEC_URL", default="http://localhost:8088")
SPLUNK_HEC_TOKEN       = env("SPLUNK_HEC_TOKEN", default="")
SPLUNK_SEARCH_URL      = env("SPLUNK_SEARCH_URL", default="https://localhost:8089")
SPLUNK_SEARCH_USER     = env("SPLUNK_SEARCH_USER", default="admin")
SPLUNK_SEARCH_PASSWORD = env("SPLUNK_SEARCH_PASSWORD", default="")
SPLUNK_VERIFY_SSL      = env.bool("SPLUNK_VERIFY_SSL", default=True)

# Loki serves push and query on the same host:port (different paths), so —
# unlike Splunk — one URL covers both.
LOKI_URL         = env("LOKI_URL", default="http://localhost:3100")
LOKI_VERIFY_SSL  = env.bool("LOKI_VERIFY_SSL", default=True)

# ========================================
# LOGGING CONFIGURATION
# ========================================
# Setup structured logging with Loki integration
try:
    from bridgesec_logging import setup_logging
    setup_logging(
        app_name="bridgesec",
        log_dir=BASE_DIR / 'logs',
        environment=os.getenv('ENVIRONMENT', 'development'),
        log_level='DEBUG',  # TEMPORARY: Set to DEBUG to see access token logs
        enable_loki=False,  # Disable Loki to prevent logging issues
    )
except Exception as e:
    import logging
    logging.warning(f"Failed to setup Loki logging: {e}. Using default logging.")

# Logging configuration
PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
LOG_DIR = os.path.join(PROJECT_ROOT, 'logs')

if not os.path.exists(LOG_DIR):
    os.makedirs(LOG_DIR)


# CLIENT_ID = env("CLIENT_ID")
# ISSUER_URL = env("ISSUER_URL")

CORS_ALLOWED_ORIGINS = env.list("CORS_ALLOWED_ORIGINS", default=[
    "http://127.0.0.1:3000",
    "https://bridgesec-fe.vercel.app",
    "http://31.97.229.6:3000",
    "http://localhost:3000",
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "http://jaggiest-stephania-autonomously.ngrok-free.dev",
])

CORS_ALLOW_CREDENTIALS = True

# Cookie settings — env-aware
# Local HTTP dev:  SameSite=Lax,  Secure=False
# Production HTTPS: SameSite=None, Secure=True  (required for cross-origin cookies)
_IS_PRODUCTION = os.environ.get("DJANGO_ENV") == "production"
SESSION_COOKIE_SAMESITE = "None" if _IS_PRODUCTION else "Lax"
SESSION_COOKIE_SECURE = _IS_PRODUCTION
SESSION_COOKIE_DOMAIN = env("SESSION_COOKIE_DOMAIN", default=None)
CSRF_COOKIE_SAMESITE = "None" if _IS_PRODUCTION else "Lax"
CSRF_COOKIE_SECURE = _IS_PRODUCTION
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,

    'formatters': {
        'verbose': {
            'format': '{asctime} | {levelname} | {tenant_id} | {module}.{funcName}:{lineno} | {message}',
            'style': '{',
        },
        'json': {
            '()': 'pythonjsonlogger.jsonlogger.JsonFormatter',
            'format': '%(asctime)s %(levelname)s %(name)s %(module)s %(funcName)s %(lineno)d %(tenant_id)s %(message)s',
            'datefmt': '%Y-%m-%dT%H:%M:%S',
        },
        'colored': {
            '()': 'colorlog.ColoredFormatter',
            'format': '%(log_color)s%(asctime)s | %(levelname)s | %(module)s.%(funcName)s:%(lineno)d | %(message)s',
            'datefmt': '%Y-%m-%d %H:%M:%S',
            'log_colors': {
                'DEBUG': 'cyan',
                'INFO': 'green',
                'WARNING': 'yellow',
                'ERROR': 'red',
                'CRITICAL': 'bold_red',
            },
        },
    },

    'filters': {
        'tenant_context': {
            '()': 'bridgesec_logging.config.TenantContextFilter',
        },
        'user_context': {
            '()': 'bridgesec_logging.config.UserContextFilter',
        },
    },

    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'colored',
            'level': 'DEBUG',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': os.path.join(LOG_DIR, 'app.log'),
            'formatter': 'verbose',
            'level': 'DEBUG',
            'filters': ['tenant_context'],
        },
        'celery_file': {
            'class': 'logging.FileHandler',
            'filename': os.path.join(LOG_DIR, 'bridgesec_celery.log'),
            'formatter': 'json',
            'level': 'DEBUG',
            'filters': ['tenant_context'],
        },
        'error_file': {
            'class': 'logging.FileHandler',
            'filename': os.path.join(LOG_DIR, 'error.log'),
            'formatter': 'verbose',
            'level': 'ERROR',
            'filters': ['tenant_context'],
        },
        # Ships each log record to whichever backend the record's tenant is
        # configured for (elasticsearch/splunk/loki — see log_router.py),
        # so /api/logs/ can read it back from the same place.
        'tenant_router': {
            '()': 'core.utils.log_router.TenantLogRouter',
            'level': 'DEBUG',
            'filters': ['tenant_context', 'user_context'],
        },
    },

    'loggers': {
        # Default logger for all modules
        '': {
            'handlers': ['console', 'file', 'error_file', 'tenant_router'],
            'level': 'INFO',
            'propagate': True,
        },
         "celery": {
            "handlers": ["console", "celery_file", "tenant_router"],
            "level": "INFO",
            "propagate": False,
        },
        "pika": {
            "handlers": ["file"],
            "level": "WARNING",  # suppress INFO logs from pika
            "propagate": False,
        },
        "urllib3": {
            "handlers": ["file"],
            "level": "WARNING",  # suppress verbose HTTP logs
            "propagate": False,
        },
        # Prevent ES client's own logs from being shipped back to ES (infinite loop)
        "elastic_transport": {
            "handlers": ["console", "file"],
            "level": "WARNING",
            "propagate": False,
        },
        "elasticsearch": {
            "handlers": ["console", "file"],
            "level": "WARNING",
            "propagate": False,
        },
    },
}

# ========================================
# OPA (Open Policy Agent) Configuration
# ========================================
OPA_URL         = env("OPA_URL", default="http://localhost:8181")
OPA_ENABLED     = env.bool("OPA_ENABLED", default=True)
OPA_TIMEOUT_SEC = env.int("OPA_TIMEOUT_SEC", default=2)

# Super Admin — optional comma-separated IP allowlist for /super-admin/login/
# Leave empty to allow from any IP.
SUPER_ADMIN_ALLOWED_IPS = env.list("SUPER_ADMIN_ALLOWED_IPS", default=[])

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "core.authentication.CustomJWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "core.permissions.rbac_permission.RolePermission",
        "core.permissions.rbac_permission.OPAPermission",
    ),
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.ScopedRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "okta_push": "10/min",
    },
}

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": env("REDIS_URL", default="redis://localhost:6379/0"),
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        },
    }
}


SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,
}

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

SWAGGER_SETTINGS = {
    'SECURITY_DEFINITIONS': {
        'Bearer': {
            'type': 'apiKey',
            'name': 'Authorization',
            'in': 'header'
        }
    },
    "USE_SESSION_AUTH": False,   # hides Django login/logout
    "LOGIN_URL": None,
    "LOGOUT_URL": None,
}

CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL")
CELERY_RESULT_BACKEND = 'core.celery_backend:MongoSRVBackend'
CELERY_MONGODB_BACKEND_SETTINGS = {
    'database': 'celery_results',
    'taskmeta_collection': 'celery_taskmeta',
}
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'

# ── Celery queues ─────────────────────────────────────────────────────────────
# Two queues keep notification delivery isolated from heavy bulk-fetch work.
#
#   default       → bulk fetch, diff, restore, all existing tasks
#   notifications → Slack / Teams / Email delivery only
#
# The dedicated notification worker listens ONLY to `notifications`, so it is
# never pulled away to process entity group tasks during a bulk fetch.
# Dashboard writes are synchronous (no queue) so they are always instant.
CELERY_TASK_QUEUES = {
    "default":       {"exchange": "default",       "routing_key": "default"},
    "notifications": {"exchange": "notifications", "routing_key": "notifications"},
}
CELERY_TASK_DEFAULT_QUEUE = "default"

# Route all notification dispatch tasks to the dedicated queue automatically.
# Any task under core.notifications.tasks.* lands on `notifications`.
# Everything else keeps going to `default`.
CELERY_TASK_ROUTES = {
    "core.notifications.tasks.*": {"queue": "notifications"},
}

# Explicitly include task modules so they are registered in every worker
# process at startup — regardless of autodiscovery behaviour.
CELERY_IMPORTS = [
    'core.tasks.bulk_tasks',
    'core.tasks.diff_tasks',
    'core.tasks.notification_tasks',
    'core.notifications.tasks',      # notification channel dispatch tasks
]

# Celery Beat — a single dispatcher task runs every 15 minutes and fires
# run_scheduled_bulk_task_for_tenant for any tenant whose local scheduled time
# matches the current UTC minute. New tenants and config changes are picked up
# automatically without restarting Beat.
from celery.schedules import crontab
CELERY_BEAT_SCHEDULE = {
    "dispatch-tenant-scheduled-runs": {
        "task": "core.tasks.bulk_tasks.dispatch_tenant_scheduled_runs",
        "schedule": crontab(minute="0,15,30,45"),
    },
}

# ── Email notifications (Resend) ─────────────────────────────────────────────
# Recipients are resolved per-tenant from Supabase notification_channels.
RESEND_API_KEY     = env("RESEND_API_KEY", default="")
DEFAULT_FROM_EMAIL = env("DEFAULT_FROM_EMAIL", default="")

# Alert when any entity's record count drops by more than this between snapshots.
# Receivers are resolved dynamically from Supabase tenant admins — no fixed address needed.
DIFF_ALERT_THRESHOLD = env.int("DIFF_ALERT_THRESHOLD", default=50)

# APScheduler is the FALLBACK scheduler, used only when Celery Beat is not running.
# It is OPT-IN: set USE_APSCHEDULER=true only in a deployment that runs APScheduler
# INSTEAD of Beat (do NOT run both — they would double-dispatch each tenant per tick).
USE_APSCHEDULER = os.environ.get("USE_APSCHEDULER", "false").lower() == "true"
