server {
    listen 80;
    server_name  31.97.229.6.com www.31.97.229.6.com;

    location /static/ {
        alias /app/static/;
    }

    location /mcp {
        proxy_pass http://mcp_server:8002/mcp;

        proxy_http_version 1.1;
        proxy_set_header Connection "";
        proxy_buffering off;
        proxy_cache off;
        proxy_read_timeout 300s;

        include proxy_params;
    }

    location / {
        proxy_pass http://web:8000;

        include proxy_params;
    }
}
