from rest_framework import serializers


class IdentityProviderOIDCSerializer(serializers.Serializer):
    name = serializers.CharField(required=True)
    authorization_url = serializers.CharField(required=True)
    authorization_binding = serializers.CharField(required=True)
    token_url = serializers.CharField(required=True)
    token_binding = serializers.CharField(required=True)
    user_info_url = serializers.CharField(required=False)
    user_info_binding = serializers.CharField(required=False)
    jwks_url = serializers.CharField(required=True)
    jwks_binding = serializers.CharField(required=True)
    scopes = serializers.ListField(required=True)
    client_id = serializers.CharField(required=True)
    client_secret = serializers.CharField(required=True)
    issuer_url = serializers.CharField(required=True)
    username_template = serializers.CharField(required=False)
    account_link_action = serializers.CharField(required=False)
    account_link_group_include = serializers.ListField(required=False)
    deprovisioned_action = serializers.CharField(required=False)
    groups_action = serializers.CharField( required=False)
    groups_assignment = serializers.ListField(required=False)
    groups_attribute = serializers.ListField(required=False)
    groups_filter = serializers.ListField(required=False)
    issuer_mode = serializers.CharField(required=False)
    max_clock_skew = serializers.IntegerField(required=False)
    pkce_required = serializers.BooleanField(required=False)
    protocol_type = serializers.CharField(required=False),
    profile_master = serializers.BooleanField(required=False)
    provisioning_action = serializers.CharField(required=False)
    request_signature_algorithm = serializers.CharField(required=False)
    request_signature_scope = serializers.CharField(required=False)
    status = serializers.CharField(required=False)
    subject_match_attribute = serializers.CharField(required=False),
    subject_match_type = serializers.CharField(required=False)
    suspended_action = serializers.CharField(required=False)
    

class IdentityProviderSAMLSerializer(serializers.Serializer):
    name = serializers.CharField(required=True)
    sso_url = serializers.CharField(required=True)
    issuer = serializers.CharField(required=True)
    kid = serializers.CharField(required=True)
    account_link_action = serializers.CharField(required=False)
    account_link_group_include = serializers.ListField(required=False)
    acs_type = serializers.CharField(required=False)
    deprovisioned_action = serializers.CharField(required=False)
    groups_action = serializers.CharField(required=False)
    groups_assignments = serializers.ListField(required=False)
    groups_attribute = serializers.CharField(required=False)
    groups_filter = serializers.ListField(required=False)
    issuer_mode = serializers.CharField(required=False)
    max_clock_skew = serializers.IntegerField(required=False)
    name_format = serializers.CharField(required=False)
    profile_master = serializers.BooleanField(required=False)
    provisioning_action = serializers.CharField(required=False)
    request_signature_algorithm = serializers.CharField(required=False)
    request_signature_scope = serializers.CharField(required=False)
    response_signature_algorithm = serializers.CharField(required=False)
    response_signature_scope = serializers.CharField(required=False)
    sso_binding = serializers.CharField(required=True)
    sso_destination = serializers.CharField(required=True)
    status = serializers.CharField(required=False)
    subject_filter = serializers.CharField(required=False)
    subject_format = serializers.ListField(required=False)
    subject_match_attribute = serializers.CharField(required=False)
    subject_match_type = serializers.CharField(required=False)
    suspended_action = serializers.CharField(required=False)
    username_template = serializers.CharField(required=False)

class IdentityProviderSocialSerializer(serializers.Serializer):
    name = serializers.CharField(required=True)
    scopes = serializers.ListField(required=True)
    type = serializers.CharField(required=True)
    account_link_action = serializers.CharField(required=False)
    account_link_group_include = serializers.ListField(required=False)
    apple_kid = serializers.CharField(required=False)
    apple_private_key = serializers.CharField(required=False)
    apple_team_id = serializers.CharField(required=False)
    client_id = serializers.CharField(required=False)
    client_secret = serializers.CharField(required=False)
    deprovisioned_action = serializers.CharField(required=False)
    groups_action = serializers.CharField(required=False)
    groups_assignments = serializers.ListField(required=False)
    groups_attribute = serializers.CharField(required=False)
    groups_filter = serializers.ListField(required=False)
    issuer_mode = serializers.CharField(required=False)
    max_clock_skew = serializers.IntegerField(required=False)
    profile_master = serializers.BooleanField(required=False)
    protocol_type = serializers.CharField(required=False)
    provisioning_action = serializers.CharField(required=False)
    status = serializers.CharField(required=False)
    subject_match_attribute = serializers.CharField(required=False)
    subject_match_type = serializers.CharField(required=False)
    suspended_action = serializers.CharField(required=False)
    username_template = serializers.CharField(required=False)