from mongoengine import ListField, StringField, BooleanField, IntField

from entities.models.base import BaseEntityModel


class IdentityProviderOIDC(BaseEntityModel):
    name = StringField(required=True)
    authorization_url = StringField(required=True)
    authorization_binding = StringField(required=True)
    token_url = StringField(required=True)
    token_binding = StringField(required=True)
    user_info_url = StringField(null = True, required=False)
    user_info_binding = StringField(null = True, required=False)
    jwks_url = StringField(required=True)
    jwks_binding = StringField(required=True)
    scopes = ListField(StringField(), required=True)
    client_id = StringField(required=True)
    client_secret = StringField(required=True)
    issuer_url = StringField(required=True)
    username_template = StringField(null = True, required=False)
    account_link_action = StringField(null = True, required=False)
    account_link_group_include = ListField(StringField(), null = True, required=False)
    deprovisioned_action = StringField(null = True, required=False)
    groups_action = StringField(null = True, required=False)
    groups_assignment = ListField(StringField(), null = True, required=False)
    groups_attribute = StringField(null = True, required=False)
    groups_filter = ListField(StringField(), null = True, required=False)
    issuer_mode = StringField(null = True, required=False)
    max_clock_skew = IntField(null = True, required=False)
    pkce_required = BooleanField(null = True, required=False)
    protocol_type = StringField(null = True, required=False)
    profile_master = BooleanField(null = True, required=False)
    provisioning_action = StringField(null = True, required=False)
    request_signature_algorithm = StringField(null = True, required=False)
    request_signature_scope = StringField(null = True, required=False)
    status = StringField(null = True, required=False)
    subject_match_attribute = StringField(null = True, required=False)
    subject_match_type = StringField(null = True, required=False)
    suspended_action = StringField(null = True, required=False)
    
    meta = {'collection': 'okta_idp_oidc'}


class IdentityProviderSAML(BaseEntityModel):
    name = StringField(required=True)
    sso_url = StringField(required=True)
    issuer = StringField(required=True)
    kid = StringField(required=True)
    account_link_action = StringField(null = True, required=False)
    account_link_group_include = ListField(StringField(), null = True, required=False)
    acs_type = StringField(null = True, required=False)
    deprovisioned_action = StringField(null = True, required=False)
    groups_action = StringField(null = True, required=False)
    groups_assignments = ListField(StringField(), null = True, required=False)
    groups_attribute = StringField(null = True, required=False)
    groups_filter = ListField(StringField(), null = True, required=False)
    issuer_mode = StringField(null = True, required=False)
    max_clock_skew = IntField(null = True, required=False)
    name_format = StringField(null = True, required=False)
    profile_master = BooleanField(null = True, required=False)
    provisioning_action = StringField(null = True, required=False)
    request_signature_algorithm = StringField(null = True, required=False)
    request_signature_scope = StringField(null = True, required=False)
    response_signature_algorithm = StringField(null = True, required=False)
    response_signature_scope = StringField(null = True, required=False)
    sso_binding = StringField(null = True, required=True)
    sso_destination = StringField(null = True, required=True)
    status = StringField(null = True, required=False)
    subject_filter = StringField(null = True, required=False)
    subject_format = ListField(StringField(), null = True, required=False)
    subject_match_attribute = StringField(null = True, required=False)
    subject_match_type = StringField(null = True, required=False)
    suspended_action = StringField(null = True, required=False)
    username_template = StringField(null = True, required=False)

    meta = {"collection": "okta_idp_saml"}


class IdentityProviderSocial(BaseEntityModel):
    name = StringField(required=True)
    scopes = ListField(StringField(), required=True)
    type = StringField(required=True)
    account_link_action = StringField(null = True, required=False)
    account_link_group_include = ListField(StringField(), null = True, required=False)
    apple_kid = StringField(null = True, required=False)
    apple_private_key = StringField(null = True, required=False)
    apple_team_id = StringField(null = True, required=False)
    client_id = StringField(null = True, required=False)
    client_secret = StringField(null = True, required=False)
    deprovisioned_action = StringField(null = True, required=False)
    groups_action = StringField(null = True, required=False)
    groups_assignments = ListField(StringField(), null = True, required=False)
    groups_attribute = StringField(null = True, required=False)
    groups_filter = ListField(StringField(), null = True, required=False)
    issuer_mode = StringField(null = True, required=False)
    max_clock_skew = IntField(null = True, required=False)
    profile_master = BooleanField(null = True, required=False)
    protocol_type = StringField(null = True, required=False)
    provisioning_action = StringField(null = True, required=False)
    status = StringField(null = True, required=False)
    subject_match_attribute = StringField(null = True, required=False)
    subject_match_type = StringField(null = True, required=False)
    suspended_action = StringField(null = True, required=False)
    username_template = StringField(null = True, required=False)

    meta = {"collection": "okta_idp_social"}
