from rest_framework import serializers


class PolicyMFASerializer(serializers.Serializer):
    name = serializers.CharField(max_length=255)
    description = serializers.CharField(max_length=255)
    duo = serializers.DictField()
    external_idps = serializers.ListField(child=serializers.DictField())
    fido_u2f = serializers.DictField()
    fido_webauthn = serializers.DictField()
    google_otp = serializers.DictField()
    groups_included = serializers.ListField(child=serializers.CharField(max_length=255))
    hotp = serializers.DictField()
    is_oie = serializers.BooleanField()
    okta_call = serializers.DictField()
    okta_email = serializers.DictField()
    okta_otp = serializers.DictField()
    okta_password = serializers.DictField()
    okta_push = serializers.DictField()
    okta_question = serializers.DictField()
    okta_sms = serializers.DictField()
    okta_verify = serializers.DictField()
    onprem_mfa = serializers.DictField()
    phone_number = serializers.DictField()
    priority = serializers.IntegerField()
    rsa_token = serializers.DictField()
    security_question = serializers.DictField()
    status = serializers.CharField(max_length=255)
    symantec_vip = serializers.DictField()
    web_authn = serializers.DictField()
    yubikey_token = serializers.DictField()


class PolicyRuleMFASerializer(serializers.Serializer):
    name = serializers.CharField(max_length=255)
    policy_id = serializers.CharField(max_length=255)
    app_exclude = serializers.ListField(child=serializers.DictField())
    app_include = serializers.ListField(child=serializers.DictField())
    enroll = serializers.CharField(max_length=255)
    network_connection = serializers.CharField(max_length=255)
    network_excludes = serializers.ListField(child=serializers.CharField(max_length=255))
    network_includes = serializers.ListField(child=serializers.CharField(max_length=255))
    priority = serializers.IntegerField()
    status = serializers.CharField(max_length=255)
    user_excluded = serializers.ListField(child=serializers.CharField(max_length=255))


class PolicyPasswordSerializer(serializers.Serializer):
    name = serializers.CharField(max_length=255)
    auth_provider = serializers.CharField(max_length=255)
    call_recovery = serializers.CharField(max_length=255)
    description = serializers.CharField(max_length=255)
    email_recovery = serializers.CharField(max_length=255)
    groups_included = serializers.ListField(child=serializers.CharField(max_length=255))
    password_auto_unlock_minutes = serializers.IntegerField()
    password_dictionary_lookup = serializers.BooleanField()
    password_exclude_first_name = serializers.BooleanField()
    password_exclude_last_name = serializers.BooleanField()
    password_exclude_username = serializers.BooleanField()
    password_expire_warn_days = serializers.IntegerField()
    password_history_count = serializers.IntegerField()
    password_lockout_notification_channels = serializers.ListField(child=serializers.CharField(max_length=255))
    password_max_age_days = serializers.IntegerField()
    password_max_lockout_attempts = serializers.IntegerField()
    password_min_age_minutes = serializers.IntegerField()
    password_min_length = serializers.IntegerField()
    password_min_lowercase = serializers.IntegerField()
    password_min_number = serializers.IntegerField()
    password_min_symbol = serializers.IntegerField()
    password_min_uppercase = serializers.IntegerField()
    password_show_lockout_failures = serializers.BooleanField()
    priority = serializers.IntegerField()
    question_min_length = serializers.IntegerField()
    question_recovery = serializers.CharField(max_length=255)
    recovery_email_token = serializers.CharField(max_length=255)
    skip_unlock = serializers.BooleanField()
    sms_recovery = serializers.CharField(max_length=255)
    status = serializers.CharField(max_length=255)  
    
class PolicyProfileEnrollmentSerializer(serializers.Serializer):
    id = serializers.CharField(max_length=255)
    name = serializers.CharField(max_length=255)
    status = serializers.CharField(max_length=255)

class PolicyProfileEnrollmentAppsSerializer(serializers.Serializer):
    policy_id = serializers.CharField(max_length=255)
    apps = serializers.ListField(child=serializers.CharField(max_length=255))

class PolicyRuleIDPDiscoverySerializer(serializers.Serializer):
    name = serializers.CharField(max_length=255)
    policy_id = serializers.CharField(max_length=255)
    app_exclude = serializers.ListField(child=serializers.DictField())
    app_include = serializers.ListField(child=serializers.DictField())
    idp_id = serializers.CharField(max_length=255)
    idp_type = serializers.CharField(max_length=255)
    network_connection = serializers.CharField(max_length=255)
    network_excludes = serializers.ListField(child=serializers.CharField(max_length=255))
    network_includes = serializers.ListField(child=serializers.CharField(max_length=255))
    platform_include = serializers.ListField(child=serializers.DictField())
    priority = serializers.IntegerField()
    status = serializers.CharField(max_length=255)
    user_identifier_attribute = serializers.CharField(max_length=255)
    user_identifier_patterns = serializers.ListField(child=serializers.DictField())
    user_identifier_type = serializers.CharField(max_length=255)