from rest_framework import serializers


class AppOauthSerializer(serializers.Serializer):
    label = serializers.CharField(required=True)
    type = serializers.CharField(required=True)
    accessibility_error_redirect_url = serializers.CharField(required=False, allow_null=True)
    accessibility_login_redirect_url = serializers.CharField(required=False, allow_null=True)
    accessibility_self_service = serializers.CharField(required=False, allow_null=True)
    admin_note = serializers.CharField(required=False, allow_null=True)
    app_links_json = serializers.CharField(required=False, allow_null=True)
    app_settings_json = serializers.CharField(required=False, allow_null=True)
    authentication_policy = serializers.CharField(required=False, allow_null=True)
    auto_key_rotation = serializers.BooleanField(required=False)
    auto_submit_toolbar = serializers.BooleanField(required=False)
    client_basic_secret = serializers.CharField(required=False, allow_null=True)
    client_id = serializers.CharField(required=False, allow_null=True)
    client_uri = serializers.CharField(required=False, allow_null=True)
    consent_method = serializers.CharField(required=False, allow_null=True)
    enduser_note = serializers.CharField(required=False, allow_null=True)
    grant_types = serializers.ListField(child=serializers.CharField(), required=False)
    groups_claim = serializers.ListField(child=serializers.CharField(), required=False)
    hide_ios = serializers.BooleanField(required=False)
    hide_web = serializers.BooleanField(required=False)
    implicit_assignment = serializers.BooleanField(required=False)
    issuer_mode = serializers.CharField(required=False, allow_null=True)
    jwks = serializers.ListField(child=serializers.CharField(), required=False)
    jwks_uri = serializers.CharField(required=False, allow_null=True)
    login_mode = serializers.CharField(required=False, allow_null=True)
    login_scopes = serializers.ListField(child=serializers.CharField(), required=False)
    login_uri = serializers.CharField(required=False, allow_null=True)
    logo = serializers.CharField(required=False, allow_null=True)
    logo_uri = serializers.CharField(required=False, allow_null=True)
    omit_secret = serializers.BooleanField(required=False)
    pkce_required = serializers.BooleanField(required=False)
    policy_uri = serializers.CharField(required=False, allow_null=True)
    post_logout_redirect_uris = serializers.ListField(child=serializers.CharField(), required=False)
    profile = serializers.CharField(required=False, allow_null=True)
    redirect_uris = serializers.ListField(child=serializers.CharField(), required=False)
    refresh_token_leeway = serializers.IntegerField(required=False)
    refresh_token_rotation = serializers.CharField(required=False, allow_null=True)
    response_types = serializers.ListField(child=serializers.CharField(), required=False)
    status = serializers.CharField(required=False, allow_null=True)
    timeouts = serializers.ListField(child=serializers.CharField(), required=False)
    token_endpoint_auth_method = serializers.CharField(required=False, allow_null=True)
    tos_uri = serializers.CharField(required=False, allow_null=True)
    user_name_template = serializers.CharField(required=False, allow_null=True)
    user_name_template_push_status = serializers.CharField(required=False, allow_null=True)
    user_name_template_suffix = serializers.CharField(required=False, allow_null=True)
    user_name_template_type = serializers.CharField(required=False, allow_null=True)
    wildcard_redirect = serializers.CharField(required=False, allow_null=True)

class AppSAMLSerializer(serializers.Serializer):
    label = serializers.CharField(required=True)
    accessibility_error_redirect_url = serializers.CharField(required=False, allow_null=True)
    accessibility_login_redirect_url = serializers.CharField(required=False, allow_null=True)
    accessibility_self_service = serializers.BooleanField(required=False, default=False)
    acs_endpoints = serializers.ListField(child=serializers.CharField(), required=False, allow_null=True)
    admin_note = serializers.CharField(required=False, allow_null=True)
    app_links_json = serializers.CharField(required=False, allow_null=True)
    app_settings_json = serializers.CharField(required=False, allow_null=True)
    assertion_signed = serializers.BooleanField(required=False, allow_null=True)
    attribute_statements = serializers.ListField(required=False, allow_null=True)
    audience = serializers.CharField(required=False, allow_null=True)
    authentication_policy = serializers.CharField(required=False, allow_null=True)
    authn_context_class_ref = serializers.CharField(required=False, allow_null=True)
    auto_submit_toolbar = serializers.BooleanField(required=False, default=False)
    default_relay_state = serializers.CharField(required=False, allow_null=True)
    destination = serializers.CharField(required=False, allow_null=True)
    digest_algorithm = serializers.CharField(required=False, allow_null=True)
    enduser_note = serializers.CharField(required=False, allow_null=True)
    hide_ios = serializers.BooleanField(required=False, allow_null=True)
    hide_web = serializers.BooleanField(required=False, allow_null=True)
    honor_force_authn = serializers.BooleanField(required=False, default=False)
    idp_issuer = serializers.CharField(required=False, allow_null=True)
    implicit_assignment = serializers.BooleanField(required=False, allow_null=True)
    inline_hook_id = serializers.CharField(required=False, allow_null=True)
    key_name = serializers.CharField(required=False, allow_null=True)
    key_years_valid = serializers.IntegerField(required=False, allow_null=True)
    logo = serializers.CharField(required=False, allow_null=True)
    preconfigured_app = serializers.CharField(required=False, allow_null=True)
    recipient = serializers.CharField(required=False, allow_null=True)
    request_compressed = serializers.BooleanField(required=False, allow_null=True)
    response_signed = serializers.BooleanField(required=False, allow_null=True)
    saml_signed_request_enabled = serializers.BooleanField(required=False, allow_null=True)
    saml_version = serializers.CharField(required=False, allow_null=True, default="2.0")
    signature_algorithm = serializers.CharField(required=False, allow_null=True)
    single_logout_certificate = serializers.CharField(required=False, allow_null=True)
    single_logout_issuer = serializers.CharField(required=False, allow_null=True)
    single_logout_url = serializers.CharField(required=False, allow_null=True)
    sp_issuer = serializers.CharField(required=False, allow_null=True)
    sso_url = serializers.CharField(required=False, allow_null=True)
    status = serializers.CharField(required=False, allow_null=True, default="ACTIVE")
    subject_name_id_format = serializers.CharField(required=False, allow_null=True)
    subject_name_id_template = serializers.CharField(required=False, allow_null=True)
    timeouts = serializers.ListField(required=False, allow_null=True)
    user_name_template = serializers.CharField(required=False, allow_null=True)
    user_name_template_push_status = serializers.CharField(required=False, allow_null=True)
    user_name_template_suffix = serializers.CharField(required=False, allow_null=True)
    user_name_template_type = serializers.CharField(required=False, allow_null=True)
    acs_endpoints_indices = serializers.ListField(required=False, allow_null=True)

class AppGroupAssignmentsSerializer(serializers.Serializer):
   app_id = serializers.CharField(required=True)
   group = serializers.ListField(child=serializers.CharField(), required=False, allow_null=True)
   timeouts = serializers.ListField(child=serializers.CharField(), required=False, allow_null=True)

class AppOuthRoleAssignmentSerializer(serializers.Serializer):
    client_id = serializers.CharField(required=True)
    type = serializers.CharField(required=True)
    resource_set = serializers.CharField(required=True)
    role = serializers.CharField(required=True)

class AppAcessPolicyAssignmentSerializer(serializers.Serializer):
    app_id = serializers.CharField(required=True)
    policy_id = serializers.CharField(required=True)

class AppPolicySignOnSerializer(serializers.Serializer):
    name = serializers.CharField(required=True)
    description = serializers.CharField(required=False, allow_null=True)
    catch_all = serializers.BooleanField(required=False, default=False)
    priority = serializers.IntegerField(required=False, allow_null=True)
    